services:
  neo4j:
    image: neo4j:5.25-community
    container_name: neo4j-hybrid
    ports:
      - "7475:7474"  # HTTP (different port to avoid conflicts)
      - "7688:7687"  # Bolt (different port to avoid conflicts)
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - graphrag_network
    platform: linux/arm64

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter-hybrid
    ports:
      - "8889:8888"  # Different port to avoid conflicts
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../../../lexical-graph:/home/jovyan/lexical-graph-src
      - jupyter_data:/home/jovyan/.jupyter
      - ~/.aws:/home/jovyan/.aws
    networks:
      - graphrag_network
    depends_on:
      - neo4j
      - postgres
    platform: linux/arm64

  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: pgvector-hybrid
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-graphrag}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - graphrag_network
    platform: linux/arm64

networks:
  graphrag_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  pgvector_data:
  jupyter_data: